import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Language = "en" | "fr" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    logout: "Logout",
    overview: "Overview",
    attendance: "Attendance",
    schedule: "Schedule",
    announcements: "Announcements",
    justifications: "Justifications",
    statistics: "Statistics",
    management: "Management",
    welcome_back: "Welcome back",
    save: "Save",
    cancel: "Cancel",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    back: "Back",
    export: "Export",
    toggle: "Toggle",
    close: "Close",
    confirm: "Confirm",
    publish: "Publish",
    actions: "Actions",
    status: "Status",
    date: "Date",
    name: "Name",
    email: "Email",
    type: "Type",
    from: "From",
    details: "Details",
    subject: "Subject",
    present: "Present",
    absent: "Absent",
    
    // Portals
    student_portal: "Student Portal",
    teacher_portal: "Teacher Portal",
    admin_panel: "Admin Panel",
    
    // Buttons & Actions
    save_attendance: "Save Attendance",
    submit_justification: "Submit Justification",
    mark_attendance: "Mark Attendance",
    manage_students: "Manage Students",
    manage_teachers: "Manage Teachers",
    manage_courses: "Manage Courses",
    manage_schedules: "Manage Schedules",
    reports: "Reports",
    support_requests: "Support Requests",
    access_dashboard: "Access Dashboard",
    learn_more: "Learn More",
    new_announcement: "New Announcement",
    find_duplicates: "Find Duplicates",
    no_duplicates_found: "No duplicates found",
    edit_mode: "Edit Mode",
    done_editing: "Done Editing",
    save_changes: "Save Changes",
    
    // Stats
    total_students: "Total Students",
    total_teachers: "Total Teachers",
    total_classes: "Total Classes",
    total_absences: "Total Absences",
    attendance_rate: "Attendance Rate",
    pending_justifications: "Pending Justifications",
    urgent_notifications: "Urgent Notifications",
    
    // Nav
    features: "Features",
    security: "Security",
    contact: "Contact",
    
    // Landing page
    hero_university: "Université AbdelHafid Boussouf – Mila",
    hero_title_1: "Modern University",
    hero_title_2: "Attendance Platform",
    hero_desc: "UniAttend is a modern digital platform designed to manage attendance, justifications, announcements, and academic communication inside the university.",
    digital_attendance: "Digital Attendance",
    smart_justifications: "Smart Justifications",
    realtime_notifications: "Real-Time Notifications",
    analytics_reports: "Analytics & Reports",
    platform_ecosystem: "Platform Ecosystem",
    three_roles_one_platform: "Three Roles, One Platform",
    ecosystem_desc: "Each role has its own dashboard, permissions, and features tailored to their needs.",
    student: "Student",
    teacher: "Teacher",
    administrator: "Administrator",
    // Student features
    attendance_history: "Attendance History",
    weekly_schedule: "Weekly Schedule",
    submit_justifications: "Submit Justifications",
    view_announcements: "View Announcements",
    receive_notifications: "Receive Notifications",
    // Teacher features
    mark_attendance_feat: "Mark Attendance",
    view_student_list: "View Student List",
    review_justifications: "Review Justifications",
    generate_reports: "Generate Reports",
    access_schedule: "Access Schedule",
    // Admin features
    account_management: "Account Management",
    attendance_monitoring: "Attendance Monitoring",
    statistics_dashboard: "Statistics Dashboard",
    reports_system: "Reports System",
    announcement_management: "Announcement Management",
    // Security section
    security_features: "Security & Features",
    built_for_trust: "Built for Trust",
    role_based_access: "Role-Based Access",
    secure_permissions: "Secure permissions per user role",
    realtime_updates: "Real-Time Updates",
    instant_sync: "Instant data synchronization",
    multi_language: "Multi-Language",
    multi_lang_desc: "English, French, Arabic (RTL)",
    schedule_management: "Schedule Management",
    secure_timetable: "Secure timetable system",
    // CTA
    ready_to_modernize: "Ready to Modernize Attendance?",
    join_uniattend: "Join UniAttend and experience the future of academic management.",
    get_started: "Get Started Now",
    // Footer
    quick_links: "Quick Links",
    login: "Login",
    footer_univ: "Université AbdelHafid Boussouf - Mila",
    modern_platform: "Modern University Attendance Platform",
    footer_rights: "Université AbdelHafid Boussouf - Mila 2020 ® Tous Droits Réservés",
    footer_copyright: "© 2026 UniAttend University Platform. Made for higher education.",
    footer_credit: "Designed & built entirely by Louay Chahdane",
    
    // Login page
    sign_in: "Sign In",
    select_role: "Select your role to continue",
    access_attendance_schedule: "Access your attendance & schedule",
    mark_attendance_manage: "Mark attendance & manage classes",
    full_platform_management: "Full platform management",
    login_title: "Login",
    enter_credentials: "Enter your credentials",
    registration_number: "Registration Number",
    email_address: "Email Address",
    password: "Password",
    forgot_password: "Forgot password?",
    demo_credentials: "Demo Credentials",
    
    // Student Dashboard
    computer_science: "Computer Science",
    recent_absences: "Recent Absences",
    course: "Course",
    justification_status: "Justification",
    open_schedule: "Open Schedule",
    absence_date: "Absence Date",
    course_name: "Course Name",
    select_course: "Select course",
    reason_for_absence: "Reason for Absence",
    explain_reason: "Explain the reason for your absence...",
    attachment_optional: "Attachment (Optional)",
    upload_pdf_jpg_png: "Upload PDF, JPG, or PNG",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    day: "Day",
    time: "Time",
    room: "Room",
    
    // Teacher Dashboard
    department_cs: "Department of Computer Science",
    my_courses: "My Courses",
    todays_classes: "Today's Classes",
    pending_reviews: "Pending Reviews",
    reg_number: "Reg. Number",
    action: "Action",
    reason: "Reason",
    reason_for_rejection: "Reason for Rejection",
    explain_rejection: "Explain why this justification is rejected...",
    confirm_reject: "Confirm Reject",
    approve: "Approve",
    reject: "Reject",
    submit_justification_teacher: "Submit Justification (Teacher)",
    submit_to_admin: "Submit your absence justification to the administration.",
    group: "Group",
    
    // Admin Dashboard
    administration: "Administration",
    panel: "Panel",
    monthly_statistics: "Monthly Statistics",
    stats_reset: "Statistics reset at the beginning of each month",
    attendance_by_level: "Attendance by Level",
    overall_attendance: "Overall Attendance",
    add_edit_remove_students: "Add, edit, remove students",
    manage_faculty: "Manage faculty members",
    timetable_config: "Timetable configuration",
    generate_export_reports: "Generate & export reports",
    review_user_requests: "Review user requests",
    title: "Title",
    announcement_title: "Announcement title",
    target_specialty: "Target Specialty",
    all_specialties: "All Specialties",
    target_year: "Target Year / Tranche",
    all_years: "All Years",
    target_group: "Target Group",
    all_groups: "All Groups",
    message: "Message",
    write_announcement: "Write your announcement...",
    target: "Target",
    normal: "Normal",
    important: "Important",
    urgent: "Urgent",
    select_department: "Select Department",
    select_year: "Select Year",
    select_tranche: "Select Tranche",
    select_group: "Select Group",
    add_group_makeup: "Add Group (Makeup)",
    add_group_makeup_desc: "Add students from other groups for makeup sessions:",
    weekly_schedule_title: "Weekly Schedule",
    day_time: "Day / Time",
    lecture: "Lecture",
    lab: "Lab",
    tutorial: "Tutorial",
    search_students: "Search students...",
    first_name: "First Name",
    last_name: "Last Name",
    specialty: "Specialty",
    level: "Level",
    birth_date: "Birth Date",
    birth_place: "Birth Place",
    edit_student: "Edit Student",
    add_student: "Add Student",
    no_students_found: "No students found",
    search_teachers: "Search teachers...",
    department: "Department",
    courses: "Courses",
    edit_teacher: "Edit Teacher",
    add_teacher: "Add Teacher",
    no_teachers_found: "No teachers found",
    student_attendance_report: "Student Attendance Report",
    course_attendance_report: "Course Attendance Report",
    absence_report: "Absence Report",
    justification_report: "Justification Report",
    full_attendance_by_student: "Full attendance report by student",
    attendance_stats_per_course: "Attendance statistics per course",
    detailed_absence_records: "Detailed absence records",
    summary_justifications: "Summary of all justifications",
    show: "Show",
    report: "Report",
    generated: "Generated",
    period: "Period",
    average_attendance: "Average Attendance",
    justified_absences: "Justified Absences",
    unjustified_absences: "Unjustified Absences",
    support_request_details: "Support Request Details",
    attachment: "Attachment",
    teacher_rejection_reason: "Teacher Rejection Reason",
    accept_justification: "Accept Justification",
    deny: "Deny",
    mark_resolved: "Mark as Resolved",
    resolve: "Resolve",
    view: "View",
    open: "Open",
    resolved: "Resolved",
    announcement_for_teachers: "For Teachers",
    announcement_for_students: "For Students",
    select_audience: "Select Audience",
    announcement_audience: "Announcement Audience",
    invalid_credentials: "Invalid credentials",
    request_account_access: "Request Account Access",
    fill_complete_info: "Fill in your complete information to request access",
    send: "Send",
    request_review_message: "Your request will be reviewed by the administration and you will receive a response within 24 hours to 4 days.",
    change_password: "Change Password",
    change_password_desc: "Go to Gmail to change your password",
    request_to_add: "Request to Add",
    request_to_add_desc: "Send your information to the administration for account creation",
    fill_teacher_info: "Fill in your information to send to the administration",
    teacher_request_review_message: "You will receive a response as soon as possible.",
    unintegrated_users: "Unintegrated",
    no_pending_requests: "No pending requests",
    added: "Added",
    view_attachment: "View Attachment",
    select: "Select",
    reg_already_exists: "This registration number already exists on the platform. Please contact the administration.",
    request_sent_success: "Your request has been sent successfully!",
    teacher_add_success: "You will be added to the platform within 24 hours.",
    teacher_add_fallback: "If not added, please contact the administration directly.",
    login_with_reg: "Login with Registration Number",
    login_with_reg_desc: "Use your registration number and password to login",
    change_gmail_password_desc: "Go to Gmail to change your Gmail password",
    select_subject: "Select Subject",
    current_subject: "Current Subject",
    add_schedule: "Add Schedule",
    scanning_pdf: "Scanning PDF",
    pdf_scan_success: "Schedule imported from PDF successfully!",
    auto_credentials_note: "Registration number and password will be auto-generated upon adding",
    invalid_data_retry: "Incorrect data, please try again",
    student_add_time: "You will be added to the platform within 24h — 1 week",
    student_add_fallback: "If not added, please contact the administration",
    add_dett: "Add Dett",
    dett: "Dett",
    dett_year: "Debt Year",
    dett_subjects: "Debt Subjects",
    dett_registrations: "Debt Registrations",
    manage_debtors: "Manage Debtors",
    manage_debtors_desc: "Review and approve debt student requests",
    send_problem: "Report Problem",
    group_problem: "Group Problem",
    schedule_problem: "Schedule/Timetable Problem",
    room_problem: "Classroom Problem",
    problem_description: "Problem Description",
    describe_problem: "Describe the problem in detail...",
    problem_sent_success: "Your request has been sent to the administration. You will receive a response via email.",
    show_file: "Show File",
    pdf_scan_partial: "Could not fully parse the PDF. Please edit manually.",
    pdf_scan_error: "Error reading the PDF file. Please try again.",
  },
  fr: {
    // Common
    logout: "Déconnexion",
    overview: "Aperçu",
    attendance: "Présence",
    schedule: "Emploi du temps",
    announcements: "Annonces",
    justifications: "Justifications",
    statistics: "Statistiques",
    management: "Gestion",
    welcome_back: "Bienvenue",
    save: "Enregistrer",
    cancel: "Annuler",
    add: "Ajouter",
    edit: "Modifier",
    delete: "Supprimer",
    search: "Rechercher",
    back: "Retour",
    export: "Exporter",
    toggle: "Basculer",
    close: "Fermer",
    confirm: "Confirmer",
    publish: "Publier",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    name: "Nom",
    email: "E-mail",
    type: "Type",
    from: "De",
    details: "Détails",
    subject: "Sujet",
    present: "Présent",
    absent: "Absent",
    
    // Portals
    student_portal: "Portail Étudiant",
    teacher_portal: "Portail Enseignant",
    admin_panel: "Panneau Admin",
    
    // Buttons & Actions
    save_attendance: "Enregistrer la présence",
    submit_justification: "Soumettre une justification",
    mark_attendance: "Marquer la présence",
    manage_students: "Gérer les étudiants",
    manage_teachers: "Gérer les enseignants",
    manage_courses: "Gérer les cours",
    manage_schedules: "Gérer les emplois du temps",
    reports: "Rapports",
    support_requests: "Demandes de support",
    access_dashboard: "Accéder au tableau de bord",
    learn_more: "En savoir plus",
    new_announcement: "Nouvelle annonce",
    find_duplicates: "Trouver les doublons",
    no_duplicates_found: "Aucun doublon trouvé",
    edit_mode: "Mode édition",
    done_editing: "Fin d'édition",
    save_changes: "Enregistrer",
    
    // Stats
    total_students: "Total Étudiants",
    total_teachers: "Total Enseignants",
    total_classes: "Total Cours",
    total_absences: "Total Absences",
    attendance_rate: "Taux de présence",
    pending_justifications: "Justifications en attente",
    urgent_notifications: "Notifications urgentes",
    
    // Nav
    features: "Fonctionnalités",
    security: "Sécurité",
    contact: "Contact",
    
    // Landing page
    hero_university: "Université AbdelHafid Boussouf – Mila",
    hero_title_1: "Plateforme Universitaire",
    hero_title_2: "de Gestion de Présence",
    hero_desc: "UniAttend est une plateforme numérique moderne conçue pour gérer la présence, les justifications, les annonces et la communication académique au sein de l'université.",
    digital_attendance: "Présence Numérique",
    smart_justifications: "Justifications Intelligentes",
    realtime_notifications: "Notifications en Temps Réel",
    analytics_reports: "Analyses & Rapports",
    platform_ecosystem: "Écosystème de la Plateforme",
    three_roles_one_platform: "Trois Rôles, Une Plateforme",
    ecosystem_desc: "Chaque rôle dispose de son propre tableau de bord, de ses autorisations et de ses fonctionnalités adaptées à ses besoins.",
    student: "Étudiant",
    teacher: "Enseignant",
    administrator: "Administrateur",
    attendance_history: "Historique de Présence",
    weekly_schedule: "Emploi du Temps Hebdomadaire",
    submit_justifications: "Soumettre des Justifications",
    view_announcements: "Voir les Annonces",
    receive_notifications: "Recevoir des Notifications",
    mark_attendance_feat: "Marquer la Présence",
    view_student_list: "Voir la Liste des Étudiants",
    review_justifications: "Examiner les Justifications",
    generate_reports: "Générer des Rapports",
    access_schedule: "Accéder à l'Emploi du Temps",
    account_management: "Gestion des Comptes",
    attendance_monitoring: "Suivi de la Présence",
    statistics_dashboard: "Tableau de Bord Statistiques",
    reports_system: "Système de Rapports",
    announcement_management: "Gestion des Annonces",
    security_features: "Sécurité & Fonctionnalités",
    built_for_trust: "Conçu pour la Confiance",
    role_based_access: "Contrôle d'Accès par Rôle",
    secure_permissions: "Permissions sécurisées par rôle utilisateur",
    realtime_updates: "Mises à Jour en Temps Réel",
    instant_sync: "Synchronisation instantanée des données",
    multi_language: "Multi-Langue",
    multi_lang_desc: "Anglais, Français, Arabe (RTL)",
    schedule_management: "Gestion des Emplois du Temps",
    secure_timetable: "Système d'emploi du temps sécurisé",
    ready_to_modernize: "Prêt à Moderniser la Présence ?",
    join_uniattend: "Rejoignez UniAttend et découvrez l'avenir de la gestion académique.",
    get_started: "Commencer Maintenant",
    quick_links: "Liens Rapides",
    login: "Connexion",
    footer_univ: "Université AbdelHafid Boussouf - Mila",
    modern_platform: "Plateforme Moderne de Gestion de Présence",
    footer_rights: "Université AbdelHafid Boussouf - Mila 2020 ® Tous Droits Réservés",
    footer_copyright: "© 2026 UniAttend Plateforme Universitaire. Conçue pour l'enseignement supérieur.",
    footer_credit: "Conçu et développé intégralement par Louay Chahdane",
    
    // Login page
    sign_in: "Se Connecter",
    select_role: "Sélectionnez votre rôle pour continuer",
    access_attendance_schedule: "Accédez à votre présence et emploi du temps",
    mark_attendance_manage: "Marquer la présence et gérer les cours",
    full_platform_management: "Gestion complète de la plateforme",
    login_title: "Connexion",
    enter_credentials: "Entrez vos identifiants",
    registration_number: "Numéro d'Inscription",
    email_address: "Adresse E-mail",
    password: "Mot de passe",
    forgot_password: "Mot de passe oublié ?",
    demo_credentials: "Identifiants de Démonstration",
    
    // Student Dashboard
    computer_science: "Informatique",
    recent_absences: "Absences Récentes",
    course: "Cours",
    justification_status: "Justification",
    open_schedule: "Ouvrir l'Emploi du Temps",
    absence_date: "Date d'Absence",
    course_name: "Nom du Cours",
    select_course: "Sélectionner le cours",
    reason_for_absence: "Raison de l'Absence",
    explain_reason: "Expliquez la raison de votre absence...",
    attachment_optional: "Pièce Jointe (Facultatif)",
    upload_pdf_jpg_png: "Télécharger PDF, JPG ou PNG",
    approved: "Approuvé",
    rejected: "Rejeté",
    pending: "En attente",
    day: "Jour",
    time: "Heure",
    room: "Salle",
    
    // Teacher Dashboard
    department_cs: "Département d'Informatique",
    my_courses: "Mes Cours",
    todays_classes: "Cours Aujourd'hui",
    pending_reviews: "Examens en Attente",
    reg_number: "N° Inscription",
    action: "Action",
    reason: "Raison",
    reason_for_rejection: "Raison du Rejet",
    explain_rejection: "Expliquez pourquoi cette justification est rejetée...",
    confirm_reject: "Confirmer le Rejet",
    approve: "Approuver",
    reject: "Rejeter",
    submit_justification_teacher: "Soumettre une Justification (Enseignant)",
    submit_to_admin: "Soumettez votre justification d'absence à l'administration.",
    group: "Groupe",
    
    // Admin Dashboard
    administration: "Administration",
    panel: "Panneau",
    monthly_statistics: "Statistiques Mensuelles",
    stats_reset: "Les statistiques sont réinitialisées au début de chaque mois",
    attendance_by_level: "Présence par Niveau",
    overall_attendance: "Présence Globale",
    add_edit_remove_students: "Ajouter, modifier, supprimer des étudiants",
    manage_faculty: "Gérer les membres du corps enseignant",
    timetable_config: "Configuration des emplois du temps",
    generate_export_reports: "Générer et exporter des rapports",
    review_user_requests: "Examiner les demandes des utilisateurs",
    title: "Titre",
    announcement_title: "Titre de l'annonce",
    target_specialty: "Spécialité Cible",
    all_specialties: "Toutes les Spécialités",
    target_year: "Année / Tranche Cible",
    all_years: "Toutes les Années",
    target_group: "Groupe Cible",
    all_groups: "Tous les Groupes",
    message: "Message",
    write_announcement: "Écrivez votre annonce...",
    target: "Cible",
    normal: "Normal",
    important: "Important",
    urgent: "Urgent",
    select_department: "Sélectionner le Département",
    select_year: "Sélectionner l'Année",
    select_tranche: "Sélectionner la Tranche",
    select_group: "Sélectionner le Groupe",
    add_group_makeup: "Ajouter un Groupe (Rattrapage)",
    add_group_makeup_desc: "Ajouter des étudiants d'autres groupes pour les séances de rattrapage :",
    weekly_schedule_title: "Emploi du Temps Hebdomadaire",
    day_time: "Jour / Heure",
    lecture: "Cours Magistral",
    lab: "Travaux Pratiques",
    tutorial: "Travaux Dirigés",
    search_students: "Rechercher des étudiants...",
    first_name: "Prénom",
    last_name: "Nom",
    specialty: "Spécialité",
    level: "Niveau",
    birth_date: "Date de Naissance",
    birth_place: "Lieu de Naissance",
    edit_student: "Modifier l'Étudiant",
    add_student: "Ajouter un Étudiant",
    no_students_found: "Aucun étudiant trouvé",
    search_teachers: "Rechercher des enseignants...",
    department: "Département",
    courses: "Cours",
    edit_teacher: "Modifier l'Enseignant",
    add_teacher: "Ajouter un Enseignant",
    no_teachers_found: "Aucun enseignant trouvé",
    student_attendance_report: "Rapport de Présence Étudiant",
    course_attendance_report: "Rapport de Présence par Cours",
    absence_report: "Rapport d'Absences",
    justification_report: "Rapport de Justifications",
    full_attendance_by_student: "Rapport complet de présence par étudiant",
    attendance_stats_per_course: "Statistiques de présence par cours",
    detailed_absence_records: "Registres détaillés des absences",
    summary_justifications: "Résumé de toutes les justifications",
    show: "Afficher",
    report: "Rapport",
    generated: "Généré",
    period: "Période",
    average_attendance: "Présence Moyenne",
    justified_absences: "Absences Justifiées",
    unjustified_absences: "Absences Non Justifiées",
    support_request_details: "Détails de la Demande de Support",
    attachment: "Pièce Jointe",
    teacher_rejection_reason: "Raison du Rejet par l'Enseignant",
    accept_justification: "Accepter la Justification",
    deny: "Refuser",
    mark_resolved: "Marquer comme Résolu",
    resolve: "Résoudre",
    view: "Voir",
    open: "Ouvert",
    resolved: "Résolu",
    announcement_for_teachers: "Pour les Enseignants",
    announcement_for_students: "Pour les Étudiants",
    select_audience: "Sélectionner le Public",
    announcement_audience: "Public de l'Annonce",
    invalid_credentials: "Identifiants invalides",
    request_account_access: "Demander l'accès au compte",
    fill_complete_info: "Remplissez vos informations complètes pour demander l'accès",
    send: "Envoyer",
    request_review_message: "Votre demande sera examinée par l'administration et vous recevrez une réponse dans un délai de 24 heures à 4 jours.",
    change_password: "Changer le mot de passe",
    change_password_desc: "Aller sur Gmail pour changer votre mot de passe",
    request_to_add: "Demander l'ajout",
    request_to_add_desc: "Envoyez vos informations à l'administration pour la création de compte",
    fill_teacher_info: "Remplissez vos informations pour les envoyer à l'administration",
    teacher_request_review_message: "Vous recevrez une réponse dans les plus brefs délais.",
    unintegrated_users: "Non intégrés",
    no_pending_requests: "Aucune demande en attente",
    added: "Ajouté",
    view_attachment: "Voir la pièce jointe",
    select: "Sélectionner",
    reg_already_exists: "Ce numéro d'inscription existe déjà sur la plateforme. Veuillez contacter l'administration.",
    request_sent_success: "Votre demande a été envoyée avec succès !",
    teacher_add_success: "Vous serez ajouté à la plateforme dans les 24 heures.",
    teacher_add_fallback: "Si vous n'êtes pas ajouté, veuillez contacter l'administration directement.",
    login_with_reg: "Connexion avec numéro d'inscription",
    login_with_reg_desc: "Utilisez votre numéro d'inscription et mot de passe",
    change_gmail_password_desc: "Allez sur Gmail pour changer votre mot de passe Gmail",
    select_subject: "Sélectionner la matière",
    current_subject: "Matière actuelle",
    add_schedule: "Ajouter un emploi du temps",
    scanning_pdf: "Scan du PDF",
    pdf_scan_success: "Emploi du temps importé depuis le PDF avec succès !",
    auto_credentials_note: "Le numéro d'inscription et le mot de passe seront générés automatiquement lors de l'ajout",
    invalid_data_retry: "Données incorrectes, veuillez réessayer",
    student_add_time: "Vous serez ajouté à la plateforme dans un délai de 24h à 1 semaine",
    student_add_fallback: "Si vous n'êtes pas ajouté, veuillez contacter l'administration",
    add_dett: "Ajouter Dette",
    dett: "Dette",
    dett_year: "Année de dette",
    dett_subjects: "Matières de dette",
    dett_registrations: "Inscriptions de dette",
    manage_debtors: "Gérer les débiteurs",
    manage_debtors_desc: "Examiner et approuver les demandes des étudiants débiteurs",
    send_problem: "Signaler un problème",
    group_problem: "Problème de groupe",
    schedule_problem: "Problème d'emploi du temps",
    room_problem: "Problème de salle",
    problem_description: "Description du problème",
    describe_problem: "Décrivez le problème en détail...",
    problem_sent_success: "Votre demande a été envoyée à l'administration. Vous recevrez une réponse par e-mail.",
    show_file: "Afficher le fichier",
    pdf_scan_partial: "Impossible d'analyser entièrement le PDF. Veuillez modifier manuellement.",
    pdf_scan_error: "Erreur lors de la lecture du fichier PDF. Veuillez réessayer.",
  },
  ar: {
    // Common
    logout: "تسجيل الخروج",
    overview: "نظرة عامة",
    attendance: "الحضور",
    schedule: "الجدول الزمني",
    announcements: "الإعلانات",
    justifications: "التبريرات",
    statistics: "الإحصائيات",
    management: "الإدارة",
    welcome_back: "مرحبًا بعودتك",
    save: "حفظ",
    cancel: "إلغاء",
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    search: "بحث",
    back: "رجوع",
    export: "تصدير",
    toggle: "تبديل",
    close: "إغلاق",
    confirm: "تأكيد",
    publish: "نشر",
    actions: "الإجراءات",
    status: "الحالة",
    date: "التاريخ",
    name: "الاسم",
    email: "البريد الإلكتروني",
    type: "النوع",
    from: "من",
    details: "التفاصيل",
    subject: "الموضوع",
    present: "حاضر",
    absent: "غائب",
    
    // Portals
    student_portal: "بوابة الطالب",
    teacher_portal: "بوابة الأستاذ",
    admin_panel: "لوحة الإدارة",
    
    // Buttons & Actions
    save_attendance: "حفظ الحضور",
    submit_justification: "تقديم تبرير",
    mark_attendance: "تسجيل الحضور",
    manage_students: "إدارة الطلاب",
    manage_teachers: "إدارة الأساتذة",
    manage_courses: "إدارة المقررات",
    manage_schedules: "إدارة الجداول",
    reports: "التقارير",
    support_requests: "طلبات الدعم",
    access_dashboard: "الدخول إلى لوحة التحكم",
    learn_more: "اعرف المزيد",
    new_announcement: "إعلان جديد",
    find_duplicates: "البحث عن التكرارات",
    no_duplicates_found: "لا توجد تكرارات",
    edit_mode: "وضع التعديل",
    done_editing: "إنهاء التعديل",
    save_changes: "حفظ التغييرات",
    
    // Stats
    total_students: "إجمالي الطلاب",
    total_teachers: "إجمالي الأساتذة",
    total_classes: "إجمالي الحصص",
    total_absences: "إجمالي الغيابات",
    attendance_rate: "نسبة الحضور",
    pending_justifications: "التبريرات المعلقة",
    urgent_notifications: "إشعارات عاجلة",
    
    // Nav
    features: "الميزات",
    security: "الأمان",
    contact: "اتصل بنا",
    
    // Landing page
    hero_university: "جامعة عبد الحفيظ بوالصوف – ميلة",
    hero_title_1: "منصة جامعية حديثة",
    hero_title_2: "لإدارة الحضور",
    hero_desc: "يوني أتند هي منصة رقمية حديثة مصممة لإدارة الحضور والتبريرات والإعلانات والتواصل الأكاديمي داخل الجامعة.",
    digital_attendance: "حضور رقمي",
    smart_justifications: "تبريرات ذكية",
    realtime_notifications: "إشعارات فورية",
    analytics_reports: "تحليلات وتقارير",
    platform_ecosystem: "منظومة المنصة",
    three_roles_one_platform: "ثلاثة أدوار، منصة واحدة",
    ecosystem_desc: "لكل دور لوحة تحكم خاصة وصلاحيات وميزات مصممة لتلبية احتياجاته.",
    student: "طالب",
    teacher: "أستاذ",
    administrator: "مسؤول",
    attendance_history: "سجل الحضور",
    weekly_schedule: "الجدول الأسبوعي",
    submit_justifications: "تقديم التبريرات",
    view_announcements: "عرض الإعلانات",
    receive_notifications: "استقبال الإشعارات",
    mark_attendance_feat: "تسجيل الحضور",
    view_student_list: "عرض قائمة الطلاب",
    review_justifications: "مراجعة التبريرات",
    generate_reports: "إنشاء التقارير",
    access_schedule: "الوصول للجدول الزمني",
    account_management: "إدارة الحسابات",
    attendance_monitoring: "مراقبة الحضور",
    statistics_dashboard: "لوحة الإحصائيات",
    reports_system: "نظام التقارير",
    announcement_management: "إدارة الإعلانات",
    security_features: "الأمان والميزات",
    built_for_trust: "مبنية على الثقة",
    role_based_access: "تحكم بالوصول حسب الدور",
    secure_permissions: "صلاحيات آمنة لكل دور مستخدم",
    realtime_updates: "تحديثات فورية",
    instant_sync: "مزامنة فورية للبيانات",
    multi_language: "متعدد اللغات",
    multi_lang_desc: "الإنجليزية، الفرنسية، العربية (RTL)",
    schedule_management: "إدارة الجدول الزمني",
    secure_timetable: "نظام جدول زمني آمن",
    ready_to_modernize: "مستعد لتحديث نظام الحضور؟",
    join_uniattend: "انضم إلى يوني أتند واختبر مستقبل الإدارة الأكاديمية.",
    get_started: "ابدأ الآن",
    quick_links: "روابط سريعة",
    login: "تسجيل الدخول",
    footer_univ: "جامعة عبد الحفيظ بوالصوف - ميلة",
    modern_platform: "منصة جامعية حديثة لإدارة الحضور",
    footer_rights: "جامعة عبد الحفيظ بوالصوف - ميلة 2020 ® جميع الحقوق محفوظة",
    footer_copyright: "© 2026 منصة يوني أتند الجامعية. مصممة للتعليم العالي.",
    footer_credit: "تصميم وبرمجة كاملة من إنجاز لؤي شحدان",
    
    // Login page
    sign_in: "تسجيل الدخول",
    select_role: "اختر دورك للمتابعة",
    access_attendance_schedule: "الوصول إلى الحضور والجدول الزمني",
    mark_attendance_manage: "تسجيل الحضور وإدارة الحصص",
    full_platform_management: "إدارة المنصة بالكامل",
    login_title: "تسجيل الدخول",
    enter_credentials: "أدخل بيانات الاعتماد الخاصة بك",
    registration_number: "رقم التسجيل",
    email_address: "عنوان البريد الإلكتروني",
    password: "كلمة المرور",
    forgot_password: "نسيت كلمة المرور؟",
    demo_credentials: "بيانات تجريبية",
    
    // Student Dashboard
    computer_science: "علوم الحاسوب",
    recent_absences: "الغيابات الأخيرة",
    course: "المقرر",
    justification_status: "التبرير",
    open_schedule: "فتح الجدول",
    absence_date: "تاريخ الغياب",
    course_name: "اسم المقرر",
    select_course: "اختر المقرر",
    reason_for_absence: "سبب الغياب",
    explain_reason: "اشرح سبب غيابك...",
    attachment_optional: "مرفق (اختياري)",
    upload_pdf_jpg_png: "رفع ملف PDF أو JPG أو PNG",
    approved: "مقبول",
    rejected: "مرفوض",
    pending: "معلق",
    day: "اليوم",
    time: "الوقت",
    room: "القاعة",
    
    // Teacher Dashboard
    department_cs: "قسم علوم الحاسوب",
    my_courses: "مقرراتي",
    todays_classes: "حصص اليوم",
    pending_reviews: "مراجعات معلقة",
    reg_number: "رقم التسجيل",
    action: "الإجراء",
    reason: "السبب",
    reason_for_rejection: "سبب الرفض",
    explain_rejection: "اشرح سبب رفض هذا التبرير...",
    confirm_reject: "تأكيد الرفض",
    approve: "قبول",
    reject: "رفض",
    submit_justification_teacher: "تقديم تبرير (أستاذ)",
    submit_to_admin: "قدم تبرير غيابك للإدارة.",
    group: "الفوج",
    
    // Admin Dashboard
    administration: "الإدارة",
    panel: "لوحة",
    monthly_statistics: "إحصائيات شهرية",
    stats_reset: "يتم تحديث الإحصائيات في بداية كل شهر",
    attendance_by_level: "الحضور حسب المستوى",
    overall_attendance: "الحضور العام",
    add_edit_remove_students: "إضافة وتعديل وحذف الطلاب",
    manage_faculty: "إدارة أعضاء هيئة التدريس",
    timetable_config: "تهيئة الجداول الزمنية",
    generate_export_reports: "إنشاء وتصدير التقارير",
    review_user_requests: "مراجعة طلبات المستخدمين",
    title: "العنوان",
    announcement_title: "عنوان الإعلان",
    target_specialty: "التخصص المستهدف",
    all_specialties: "جميع التخصصات",
    target_year: "السنة / الشعبة المستهدفة",
    all_years: "جميع السنوات",
    target_group: "الفوج المستهدف",
    all_groups: "جميع الأفواج",
    message: "الرسالة",
    write_announcement: "اكتب إعلانك...",
    target: "الهدف",
    normal: "عادي",
    important: "مهم",
    urgent: "عاجل",
    select_department: "اختر القسم",
    select_year: "اختر السنة",
    select_tranche: "اختر الشعبة",
    select_group: "اختر الفوج",
    add_group_makeup: "إضافة فوج (تعويض)",
    add_group_makeup_desc: "إضافة طلاب من أفواج أخرى لحصص التعويض:",
    weekly_schedule_title: "الجدول الأسبوعي",
    day_time: "اليوم / الوقت",
    lecture: "محاضرة",
    lab: "أعمال تطبيقية",
    tutorial: "أعمال موجهة",
    search_students: "البحث عن طلاب...",
    first_name: "الاسم",
    last_name: "اللقب",
    specialty: "التخصص",
    level: "المستوى",
    birth_date: "تاريخ الميلاد",
    birth_place: "مكان الميلاد",
    edit_student: "تعديل الطالب",
    add_student: "إضافة طالب",
    no_students_found: "لم يتم العثور على طلاب",
    search_teachers: "البحث عن أساتذة...",
    department: "القسم",
    courses: "المقررات",
    edit_teacher: "تعديل الأستاذ",
    add_teacher: "إضافة أستاذ",
    no_teachers_found: "لم يتم العثور على أساتذة",
    student_attendance_report: "تقرير حضور الطالب",
    course_attendance_report: "تقرير حضور المقرر",
    absence_report: "تقرير الغيابات",
    justification_report: "تقرير التبريرات",
    full_attendance_by_student: "تقرير حضور كامل لكل طالب",
    attendance_stats_per_course: "إحصائيات الحضور لكل مقرر",
    detailed_absence_records: "سجلات الغياب المفصلة",
    summary_justifications: "ملخص جميع التبريرات",
    show: "عرض",
    report: "تقرير",
    generated: "تم الإنشاء",
    period: "الفترة",
    average_attendance: "متوسط الحضور",
    justified_absences: "غيابات مبررة",
    unjustified_absences: "غيابات غير مبررة",
    support_request_details: "تفاصيل طلب الدعم",
    attachment: "مرفق",
    teacher_rejection_reason: "سبب رفض الأستاذ",
    accept_justification: "قبول التبرير",
    deny: "رفض",
    mark_resolved: "وضع علامة محلول",
    resolve: "حل",
    view: "عرض",
    open: "مفتوح",
    resolved: "محلول",
    announcement_for_teachers: "للأساتذة",
    announcement_for_students: "للطلاب",
    select_audience: "اختر الجمهور",
    announcement_audience: "جمهور الإعلان",
    invalid_credentials: "بيانات الاعتماد غير صحيحة",
    request_account_access: "طلب الوصول للحساب",
    fill_complete_info: "أدخل معلوماتك الكاملة لطلب الوصول",
    send: "إرسال",
    request_review_message: "سيتم عرض طلبك للجهات المعنية والرد خلال 24 ساعة إلى 4 أيام.",
    change_password: "تغيير كلمة المرور",
    change_password_desc: "الانتقال إلى Gmail لتغيير كلمة المرور",
    request_to_add: "طلب الإضافة",
    request_to_add_desc: "أرسل معلوماتك للإدارة لإنشاء حساب",
    fill_teacher_info: "أدخل معلوماتك لإرسالها للإدارة",
    teacher_request_review_message: "سيتم الرد عليك في أسرع وقت.",
    unintegrated_users: "غير المدمجين",
    no_pending_requests: "لا توجد طلبات معلقة",
    added: "تمت الإضافة",
    view_attachment: "عرض المرفق",
    select: "اختر",
    reg_already_exists: "رقم التسجيل هذا موجود بالفعل في الموقع. يرجى التوجه للإدارة.",
    request_sent_success: "تم إرسال طلبك بنجاح!",
    teacher_add_success: "سيتم إضافتك للموقع في غضون 24 ساعة.",
    teacher_add_fallback: "إن لم تُضف، اتجه للإدارة.",
    login_with_reg: "الدخول برقم التسجيل",
    login_with_reg_desc: "استخدم رقم التسجيل وكلمة المرور للدخول",
    change_gmail_password_desc: "الانتقال إلى Gmail لتغيير كلمة مرور Gmail",
    select_subject: "اختر المادة",
    current_subject: "المادة الحالية",
    add_schedule: "إضافة جدول",
    scanning_pdf: "جاري فحص الملف",
    pdf_scan_success: "تم استيراد الجدول من الملف بنجاح!",
    auto_credentials_note: "سيتم إنشاء رقم التسجيل وكلمة المرور تلقائياً عند الإضافة",
    invalid_data_retry: "البيانات غير صحيحة، أعد المحاولة",
    student_add_time: "سيتم إضافتك للموقع في غضون 24 ساعة إلى أسبوع",
    student_add_fallback: "إن لم تُضف، اتجه للإدارة",
    add_dett: "إضافة دين",
    dett: "مديون",
    dett_year: "سنة الدين",
    dett_subjects: "مواد الدين",
    dett_registrations: "تسجيلات الدين",
    manage_debtors: "إدارة المديونين",
    manage_debtors_desc: "مراجعة وقبول طلبات الطلاب المديونين",
    send_problem: "إرسال مشكل",
    group_problem: "مشكل في الفوج",
    schedule_problem: "مشكل في التوقيت والجدول",
    room_problem: "مشكل في قاعة التدريس",
    problem_description: "وصف المشكل",
    describe_problem: "اشرح المشكل بالتفصيل...",
    problem_sent_success: "تم إرسال طلبك إلى الإدارة. سيتم الرد على مستوى الإيميل.",
    show_file: "إظهار الملف",
    pdf_scan_partial: "لم يتم تحليل الملف بالكامل. يرجى التعديل يدوياً.",
    pdf_scan_error: "خطأ في قراءة ملف PDF. يرجى المحاولة مرة أخرى.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("uniattend-lang");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("uniattend-lang", lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
